# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
swift_version = "5.0"

def pods
  pod 'Alamofire'
  
  pod 'Zip'

  pod 'Fabric'
  pod 'Crashlytics'
end

target 'DaTracker' do
  pods
end

target 'DaTrackerTests' do
   inherit! :search_paths
   # Pods for testing
end

target 'DaTrackerUITests' do
   inherit! :search_paths
   # Pods for testing
 end
