# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DaTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  swift_version = "4.2"

   pod 'Zip'
  
  # Pods for DaTracker

  target 'DaTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DaTrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
